### ISSUE TITLE
Upgrading mbed-os to 5.10.2 no longer connects

### ISSUE THREAD

**Issue by mray190** [Avnet/wnc14a2a-driver#15]
No longer can connect to a network when I upgraded mbed-os to `5.10.2`

Tries to connect and then fails with a -3004 error after 3 connection attempts

**Comment by ghost** [comment]
This works ok with a version <5.10.2?

**Comment by mray190** [comment]
@jflynn129 false alarm, I did not have the external power supply hooked up to the cell shield
