### ISSUE TITLE
Serial is created when it's not necessary.

### ISSUE THREAD

**Issue by coisme** [Avnet/wnc14a2a-driver#6]
Since a Serial instance is created at the global scope, it's created when it's not necessary. This causes a bug in easy_connect even WIFI_ESP8266 is used.

https://github.com/Avnet/wnc14a2a-driver/blob/014628fb0171444d1022b00fc6304830682a12b4/WNC14A2AInterface/WNC14A2AInterface.cpp#L175

**Comment by jflynn129** [comment]
Thank you I’ll work on a resolution.

**Comment by coisme** [comment]
Thank you for correction. This part causes another problem in my program:
https://github.com/Avnet/wnc14a2a-driver/blob/52a50d2eeb8c61b5bcfd48b3f6f3cd3f68dca66c/WNC14A2AInterface/WNC14A2AInterface.cpp#L156-L161
Could you remove them from global scope?

**Comment by coisme** [comment]
FYI, you can find a guideline here -- in _API design - user API_:
https://os.mbed.com/docs/v5.8/reference/guidelines.html#software-design
> Do not declare objects in global scope (applications should allocate global objects). Objects declared in global scope rarely get garbage-collected by compilers during link time. This can cause significant bloat in the size of an application.
This time, the reason to avoid global scope is different from above. In the current program, the objects above, they use pins, are instantiated at start up time before main function is called, even if your module is unused. These pins may conflicts with the pins used in application program.

**Comment by coisme** [comment]
My problem solved was solved by your change. Thanks!

**Comment by jflynn129** [comment]
I will do a new release tomorrow in which I removed all the global scoped variables, just need to finish testing it. Thanks for your patients.
